---
- name: Start Dashy
  block:
    - name: Create Dashy Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dashy_data_directory }}"
        - "{{ dashy_data_directory }}/dashboard-icons"
        - "{{ dashy_icon_directory }}"

    - name: Copy base config
      ansible.builtin.copy:
        src: conf.yml
        dest: "{{ dashy_data_directory }}/conf.yml"
        force: no

    - name: Clone dashboard-icons repository
      ansible.builtin.git:
        repo: https://github.com/walkxcode/dashboard-icons.git
        dest: "{{ dashy_data_directory }}/dashboard-icons"
        version: HEAD

    - name: Copy contents of png folder
      ansible.builtin.copy:
        src: "{{ dashy_data_directory }}/dashboard-icons/png/"
        dest: "{{ dashy_icon_directory }}/png"
        remote_src: yes
        force: yes

    - name: Delete cloned dashboard-icons repository
      ansible.builtin.file:
        path: "{{ dashy_data_directory }}/dashboard-icons"
        state: absent

    - name: Clone MaterialDesign repository
      ansible.builtin.git:
        repo: https://github.com/Templarian/MaterialDesign.git
        dest: "{{ dashy_data_directory }}/material-design"
        version: HEAD

    - name: Copy svg folder
      ansible.builtin.copy:
        src: "{{ dashy_data_directory }}/material-design/svg/"
        dest: "{{ dashy_icon_directory }}/svg"
        remote_src: yes
        force: yes

    - name: Delete cloned MaterialDesign repository
      ansible.builtin.file:
        path: "{{ dashy_data_directory }}/material-design"
        state: absent

    - name: Dashy Docker Container
      community.docker.docker_container:
        name: "{{ dashy_container_name }}"
        image: lissy93/dashy:latest
        pull: true
        ports:
          - "{{ dashy_port }}:8080"
        restart_policy: unless-stopped
        memory: "{{ dashy_memory }}"
        volumes:
          - "{{ dashy_data_directory }}/conf.yml:/app/public/conf.yml:rw"
          - "{{ dashy_icon_directory }}:/app/public/item-icons/:rw"
        labels:
          traefik.enable: "{{ dashy_available_externally | string }}"
          traefik.http.routers.dashy.rule: "Host(`{{ dashy_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dashy.tls.certresolver: "letsencrypt"
          traefik.http.routers.dashy.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dashy.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.dashy.loadbalancer.server.port: "80"
  when: dashy_enabled is true

- name: Stop Dashy
  block:
    - name: Stop Dashy
      community.docker.docker_container:
        name: "{{ dashy_container_name }}"
        state: absent
  when: dashy_enabled is false
