---
nextcloud_enabled: false
nextcloud_available_externally: true

# directories
nextcloud_data_directory: "{{ docker_home }}/nextcloud"
nextcloud_storage_directory: "{{ ansible_nas_storage_volume }}/nextcloud"

# network
nextcloud_port: "8080"
nextcloud_hostname: "nextcloud"
nextcloud_network_name: "nextcloud"

# docker
nextcloud_container_name: "nextcloud"
nextcloud_image_name: "nextcloud"
nextcloud_image_version: "stable"
nextcloud_db_container_name: "nextcloud-db"
nextcloud_db_image_name: "mysql"
nextcloud_db_image_version: "8.3"

# specs
nextcloud_memory: 1g
nextcloud_db_memory: 1g
