---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get container state
      community.docker.docker_container_info:
        name: "{{ adguard_home_container_name }}"
      register: result

    - name: Check AdGuard Home is running
      ansible.builtin.assert:
        that:
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
