---
- name: start immich
  block:
    - name: Create Immich Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ immich_upload_directory }}"
        - "{{ immich_data_directory }}"

    - name: Create Immich Docker network
      community.docker.docker_network:
        name: "{{ immich_network_name }}"

    - name: Immich Postgres Docker container
      community.docker.docker_container:
          name: immich_postgres
          image: "ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1"
          env:
            POSTGRES_PASSWORD: "{{ immich_db_password }}"
            POSTGRES_USER: "{{ immich_db_username }}"
            POSTGRES_DB: "{{ immich_db_name }}"
            POSTGRES_INITDB_ARGS: '--data-checksums'
            # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
            # DB_STORAGE_TYPE: 'HDD'
          volumes:
            # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
            - "{{ immich_data_directory }}:/var/lib/postgresql/data"
          restart_policy: unless-stopped
          memory: "{{ immich_postgres_memory }}"
          networks:
            - name: "{{ immich_network_name }}"
              aliases: database
    
    - name: Immich Redis Docker container
      community.docker.docker_container:
        name: immich_redis
        image: "docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884"
        healthcheck:
          test: redis-cli ping || exit 1
        restart_policy: unless-stopped
        memory: "{{ immich_redis_memory }}"
        networks:
          - name: "{{ immich_network_name }}"
            aliases: redis   

    - name: Immich Docker container
      community.docker.docker_container:
        name: immich_server
        image: "ghcr.io/immich-app/immich-server:{{ immich_version }}"
        # extends:
        #   file: hwaccel.transcoding.yml
        #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
        volumes:
        # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
          - "{{ immich_upload_directory }}:/usr/src/app/upload"
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ immich_external_directory }}:/photos:rw"
        env: "{{ immich_env }}"
        ports:
          - "{{ immich_port }}:2283"
        restart_policy: unless-stopped
        memory: "{{ immich_server_memory }}"
        networks:
          - name: "{{ immich_network_name }}"   
        labels:
          traefik.enable: "{{ immich_available_externally | string }}"
          traefik.http.routers.immich.rule: "Host(`{{ immich_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.immich.tls.certresolver: "letsencrypt"
          traefik.http.routers.immich.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.immich.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.immich.loadbalancer.server.port: "2283"
          homepage.group: Media
          homepage.name: Immich
          homepage.icon: immich.png
          homepage.href: "{% if immich_available_externally %}https://{{ immich_hostname }}.{{ ansible_nas_domain }}{% else %}http://{{ ansible_nas_hostname }}:{{ immich_port }}{% endif %}"
          homepage.description: Photo & video management

    - name: Immich Machine Learning Docker container
      community.docker.docker_container:
        name: immich_machine_learning
        # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
        # Example tag: ${IMMICH_VERSION:-release}-cuda
        image: "ghcr.io/immich-app/immich-machine-learning:{{ immich_version }}"
        # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        #   file: hwaccel.ml.yml
        #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
        volumes:
          - model-cache:/cache
          - "{{ immich_external_directory }}:/photos:rw"
        env: "{{ immich_env }}"
        restart_policy: unless-stopped
        memory: "{{ immich_machinelearning_memory }}"
        networks:
          - name: "{{ immich_network_name }}"

- name: Stop Immich
  block:
    - name: Stop Immich Postgres
      community.docker.docker_container:
        name: immich_postgres
        state: absent

    - name: Stop Immich Redis
      community.docker.docker_container:
        name: immich_redis
        state: absent

    - name: Stop Immich Server
      community.docker.docker_container:
        name: immich_server
        state: absent

    - name: Stop Immich Machine Learning
      community.docker.docker_container:
        name: immich_machine_learning
        state: absent

    - name: Delete Immich Network
      community.docker.docker_network:
        name: "{{ immich_network_name }}"
        state: absent

  when: immich_enabled is false