---
# Update all apt packages when playbook is run
keep_packages_updated: true

# Extra packages to install
ansible_nas_extra_packages:
  - smartmontools
  - htop
  - zfsutils-linux
  - bonnie++
  - unzip
  - lm-sensors
#  - ctop