---
- name: Start profilarr
  block:
    - name: Create profilarr Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ profilarr_data_directory }}"

    - name: Create arr Docker Network
      community.docker.docker_network:
        name: "arr"

    - name: profilarr
      community.docker.docker_container:
        name: "{{ profilarr_container_name }}"
        image: santiagosayshey/profilarr:latest
        pull: true
        ports:
          - "{{ profilarr_port }}:6868"
        #user: "{{ profilarr_user_id }}:{{ profilarr_group_id }}"
        volumes:
          - "{{ profilarr_data_directory }}/config:/config:rw"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
        memory: "{{ profilarr_memory }}"
        networks:
          - name: "arr"
        network_mode: "arr"
        labels: >-
          {{
            {
              "traefik.enable": "true",
              "traefik.http.routers.profilarr-local.rule": "Host(`" + profilarr_hostname + "." + ansible_nas_local_domain + "`)",
              "traefik.http.routers.profilarr-local.entrypoints": "websecure",
              "traefik.http.routers.profilarr-local.tls": "true",
              "traefik.http.services.profilarr.loadbalancer.server.port": "6868",
              "homepage.group": "Download Tools",
              "homepage.name": "profilarr",
              "homepage.icon": "profilarr",
              "homepage.description": "TV series manager for Usenet and BitTorrent.",
              "homepage.href": ("https://" + profilarr_hostname + "." + ansible_nas_domain) if profilarr_available_externally else ("https://" + profilarr_hostname + "." + ansible_nas_local_domain)
            } | combine(
              {
                "traefik.http.routers.profilarr.rule": "Host(`" + profilarr_hostname + "." + ansible_nas_domain + "`)",
                "traefik.http.routers.profilarr.entrypoints": "websecure",
                "traefik.http.routers.profilarr.tls.certresolver": "letsencrypt",
                "traefik.http.routers.profilarr.tls.domains[0].main": ansible_nas_domain,
                "traefik.http.routers.profilarr.tls.domains[0].sans": "*." + ansible_nas_domain
              } if profilarr_available_externally else {}
            )
          }}
  when: profilarr_enabled is true

- name: Stop profilarr
  block:
    - name: Stop profilarr
      community.docker.docker_container:
        name: "{{ profilarr_container_name }}"
        state: absent
  when: profilarr_enabled is false
