# With this options you can disable or enable processing for *arrs. Default is enabled
#sonarrEnabled: false
#radarrEnabled: false
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

# Radarr Configuration
radarr:
  instance1: # Instance name (can be any unique identifier)
    base_url: http://radarr:7878 # Radarr instance URL
    api_key: !secret RADARR_API_KEY # Reference to API key in secrets.yml
    media_naming:
      folder: default
      movie:
        rename: true
        standard: default
    include:
      - template: 2b90e905c99490edc7c7a5787443748b
        source: TRASH
    {
      "name": "[HDR Formats] - Block",
      "trash_id": "d9acca37ab4ab8f6428b68125fc0cacb",
      "trash_description": "Penalize all HDR formats to avoid HDR releases. Score: -10000",
      "default": false,
      "custom_formats": [
        {
          "name": "DV HDR10Plus",
          "trash_id": "c53085ddbd027d9624b320627748612f",
          "score": -10000
        },
        {
          "name": "DV HDR10",
          "trash_id": "e23edd2482476e595fb990b12e7c609c",
          "score": -10000
        },
        {
          "name": "DV",
          "trash_id": "58d6a88f13e2db7f5059c41047876f00",
          "score": -10000
        },
        {
          "name": "DV HLG",
          "trash_id": "55d53828b9d81cbe20b02efd00aa0efd",
          "score": -10000
        },
        {
          "name": "DV SDR",
          "trash_id": "a3e19f8f627608af0211acd02bf89735",
          "score": -10000
        },
        {
          "name": "HDR10+",
          "trash_id": "b974a6cd08c1066250f1f177d7aa1225",
          "score": -10000
        },
        {
          "name": "HDR10",
          "trash_id": "dfb86d5941bc9075d6af23b09c2aeecd",
          "score": -10000
        },
        {
          "name": "HDR",
          "trash_id": "e61e28db95d22bedcadf030b8f156d96",
          "score": -10000
        },
        {
          "name": "HDR (Undefined)",
          "trash_id": "2a4d9069cc1fe3242ff9bdaebed239bb",
          "score": -10000
        },
        {
          "name": "PQ",
          "trash_id": "08d6d8834ad9ec87b1dc7ec8148e7a1f",
          "score": -10000
        },
        {
          "name": "HLG",
          "trash_id": "9364dd386c9b4a1100dde8264690add7",
          "score": -10000
        }
      ]
    }


# Sonarr Configuration
sonarr:
  instance1: # Instance name (can be any unique identifier)
    base_url: http://sonarr:8989 # Sonarr instance URL
    api_key: !secret SONARR_API_KEY # Reference to API key in secrets.yml
    # api_key: !env SONARR_API_KEY # load from environment variable
    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default