---
- name: Create AdGuard Home Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ adguard_home_user_id }}"
    group: "{{ adguard_home_group_id }}"
  with_items:
    - "{{ adguard_home_data_directory }}/work"
    - "{{ adguard_home_data_directory }}/conf"
  when: adguard_home_enabled

- name: Check if AdGuard Home is already configured
  ansible.builtin.stat:
    path: "{{ adguard_home_data_directory }}/conf/AdGuardHome.yaml"
  register: adguard_config
  when: adguard_home_enabled

- name: Initialize AdGuard Home (first run only)
  community.docker.docker_container:
    name: "{{ adguard_home_container_name }}_init"
    image: "{{ adguard_home_image }}:{{ adguard_home_tag }}"
    pull: true
    # Run as root for initialization
    capabilities:
      - NET_BIND_SERVICE
      - NET_RAW
    ports:
      - "{{ adguard_home_port_http }}:3000"
      - "{{ ansible_nas_ipv4_address }}:{{ adguard_home_port_dns }}:53/udp"
      - "{{ ansible_nas_ipv4_address }}:{{ adguard_home_port_dns_tcp }}:53/tcp"
      - "{{ ansible_nas_ipv4_address }}:{{ adguard_home_port_tls }}:853/tcp"
      - "{{ ansible_nas_ipv4_address }}:{{ adguard_home_port_quic }}:784/udp"
    volumes:
      - "{{ adguard_home_data_directory }}/conf:/opt/adguardhome/conf"
      - "{{ adguard_home_data_directory }}/work:/opt/adguardhome/work"
    command: "--no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -w /opt/adguardhome/work --no-permcheck"
    detach: false
    cleanup: true
  when: adguard_home_enabled and not adguard_config.stat.exists

- name: Fix permissions after initialization
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ adguard_home_user_id }}"
    group: "{{ adguard_home_group_id }}"
  with_items:
    - "{{ adguard_home_data_directory }}/work"
    - "{{ adguard_home_data_directory }}/conf"
  when: adguard_home_enabled

- name: AdGuard Home Docker Container
  docker_container:
    name: "{{ adguard_home_container_name }}"
    image: "{{ adguard_home_image }}:{{ adguard_home_tag }}"
    pull: true
    user: "{{ adguard_home_user_id }}:{{ adguard_home_group_id }}"
    capabilities:
      - NET_BIND_SERVICE
      - NET_RAW
    volumes:
      - "{{ adguard_home_data_directory }}/conf:/opt/adguardhome/conf"
      - "{{ adguard_home_data_directory }}/work:/opt/adguardhome/work"
    ports:
      - "{{ adguard_home_port_http }}:3000"
      - "{{ ansible_nas_ipv4_address }}:{{ adguard_home_port_dns }}:53/udp"
      - "{{ ansible_nas_ipv4_address }}:{{ adguard_home_port_dns_tcp }}:53/tcp"
      - "{{ ansible_nas_ipv4_address }}:{{ adguard_home_port_tls }}:853/tcp"
      - "{{ ansible_nas_ipv4_address }}:{{ adguard_home_port_quic }}:784/udp"
    restart_policy: unless-stopped
    memory: "{{ adguard_home_memory }}"
    labels:
      traefik.enable: "{{ adguard_home_available_externally | string }}"
      traefik.http.routers.adguard-home.rule: "Host(`{{ adguard_home_container_name }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.adguard-home.tls.certresolver: "letsencrypt"
      traefik.http.services.adguard-home.loadbalancer.server.port: "80"
      homepage.name: "AdGuard Home"
      homepage.description: "DNS server"
      homepage.group: "Networking"
      homepage.icon: "adguard-home.png"
      homepage.href: "{% if adguard_home_available_externally %}https://{{ adguard_home_container_name }}.{{ ansible_nas_domain }}{% else %}http://{{ ansible_nas_hostname }}:{{ adguard_home_port_http }}{% endif %}"
  when: adguard_home_enabled

- name: Stop AdGuard Home
  block:
    - name: Stop AdGuard Home Container
      docker_container:
        name: "{{ adguard_home_container_name }}"
        state: absent
  when: not adguard_home_enabled