---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove Profilarr
      community.docker.docker_container:
        name: "{{ profilarr_container_name }}"
        state: absent
      register: result

    - name: Check Profilarr is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
