# enable or disable the application
immich_enabled: false
immich_available_externally: false

# directories
immich_data_directory: "{{ docker_home }}/immich"
immich_upload_directory: "{{ ansible_nas_storage_volume }}/photos/immich"
immich_external_directory: "{{ ansible_nas_storage_volume }}/photos"

# network
immich_hostname: "immich"
immich_port: "2283"
immich_network_name: "immich_network"

#user
immich_user_id: "1000"
immich_group_id: "1000"

# specs	
immich_server_memory: "4g"
immich_machinelearning_memory: "4g"
immich_postgres_memory: "1g"
immich_redis_memory: "1g"

# database
#immich_db_password: "postgres" # Set DB password in nas.yml, use a secure random string generator
immich_db_username: "postgres"
immich_db_name: "immich"

immich_version: "release"  # Set to "latest" for the latest version, or a specific version tag

immich_env:
  UPLOAD_LOCATION: "{{ immich_upload_directory }}"
  DB_DATA_LOCATION: "{{ immich_data_directory }}"
  TZ: "{{ ansible_nas_timezone }}"
  IMMICH_VERSION: "{{ immich_version }}"
  DB_PASSWORD: "{{ immich_db_password }}"
  DB_USERNAME: "{{ immich_db_username }}"
  DB_DATABASE_NAME: "{{ immich_db_name }}"
  UID: "{{ immich_user_id }}"
  GID: "{{ immich_group_id }}"